hardware_interface:
  sim_control_mode: 0
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
generic_hw_control_loop:
  loop_hz: &loop_rate 100
  cycle_time_error_threshold: 0.015
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: *loop_rate
whole_body_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
